sudo: required
services:
  docker

before_install:
  - docker build -t edidock901/docker-react -f Dockerfile.dev .

script:
  - docker run edidock901/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-520451559009"
  bucket_path: "docker-react1"
  on:
    branch: master
  access_key_id:
    secure: "AKIAXSLKURZQV35LDYYS"
  secret_access_key:
    secure: "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"